name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install packages
        shell: bash
        run: npm install
      - name: Build app
        shell: bash
        run: npm run build
      - name: Deploy to GitHub Pages
        shell: bash
        run: |
          cd dist
          ln -s index.html 404.html
          git init
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main:gh-pages